frameworkVersion: '3'
configValidationMode: error

org: godrm
app: godrm
service: godrm-api

plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-optimize

provider:
  # General settings
  name: aws
  stage: ${sls:stage}
  region: ap-northeast-1

  deploymentMethod: direct
  # API Gateway settings
  apiName: ${self:service}-${sls:stage}

  # Function settings
  runtime: nodejs14.x
  timeout: 10 # default: 6s

  environment:
    DATABASE_URI: ${param:DATABASE_URI}
    NODE_ENV: ${param:NODE_ENV}
    TOKEN_SECRET: ${param:TOKEN_SECRET}

custom:
  domain:
    dev: godrm-dev.api-server.link
    prod: godrm.api-server.link
  customDomain:
    domainName: ${self:custom.domain.${opt:stage, 'dev'}}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  optimize:
    external: ["swagger-ui-dist"]

package:
  individually: true

functions:
  auth:
    handler: apps/auth/src/main.handler
    events:
      - http:
          method: ANY
          path: /auth
      - http:
          method: ANY
          path: /auth/{proxy+}
  user:
    handler: apps/user/src/main.handler
    events:
      - http:
          method: ANY
          path: /users
      - http:
          method: ANY
          path: /users/{proxy+}
  food:
    handler: apps/food/src/main.handler
    events:
      - http:
          method: ANY
          path: /food
      - http:
          method: ANY
          path: /food/{proxy+}
  category:
    handler: apps/category/src/main.handler
    events:
      - http:
          method: ANY
          path: /category # base: / route: category
      - http:
          method: ANY
          path: /category/{proxy+} # base: /category route: {proxy+}
  favourite:
    handler: apps/favourite/src/main.handler
    events:
      - http:
          method: ANY
          path: /favourite
      - http:
          method: ANY
          path: /favourite/{proxy+}
  shopping-cart:
    handler: apps/shopping-cart/src/main.handler
    events:
      - http:
          method: ANY
          path: /cart
      - http:
          method: ANY
          path: /cart/{proxy+}
